"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const requisition_controller_1 = require("./requisition.controller");
const authenticate_1 = require("../../middleware/authenticate");
const authorize_1 = require("../../middleware/authorize");
const validate_1 = require("../../middleware/validate");
const permissions_1 = require("../../rbac/permissions");
const router = (0, express_1.Router)();
router.use(authenticate_1.authenticate);
router.get('/', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.REQUISITIONS_READ), requisition_controller_1.RequisitionController.list);
router.get('/:id', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.REQUISITIONS_READ), requisition_controller_1.RequisitionController.getById);
router.post('/', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.REQUISITIONS_CREATE), (0, validate_1.validateBody)(requisition_controller_1.createRequisitionSchema), requisition_controller_1.RequisitionController.create);
router.put('/:id', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.REQUISITIONS_UPDATE), (0, validate_1.validateBody)(requisition_controller_1.updateRequisitionSchema), requisition_controller_1.RequisitionController.update);
router.post('/:id/approve', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.REQUISITIONS_APPROVE), (0, validate_1.validateBody)(requisition_controller_1.approveRequisitionSchema), requisition_controller_1.RequisitionController.approve);
exports.default = router;
