"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const job_controller_1 = require("./job.controller");
const authenticate_1 = require("../../middleware/authenticate");
const authorize_1 = require("../../middleware/authorize");
const validate_1 = require("../../middleware/validate");
const permissions_1 = require("../../rbac/permissions");
const router = (0, express_1.Router)();
router.use(authenticate_1.authenticate);
router.get('/', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.JOBS_READ), job_controller_1.JobController.list);
router.get('/:id', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.JOBS_READ), job_controller_1.JobController.getById);
router.post('/', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.JOBS_CREATE), (0, validate_1.validateBody)(job_controller_1.createJobSchema), job_controller_1.JobController.create);
router.put('/:id', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.JOBS_UPDATE), (0, validate_1.validateBody)(job_controller_1.updateJobSchema), job_controller_1.JobController.update);
router.post('/:id/publish', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.JOBS_PUBLISH), job_controller_1.JobController.publish);
exports.default = router;
