"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const offer_controller_1 = require("./offer.controller");
const authenticate_1 = require("../../middleware/authenticate");
const authorize_1 = require("../../middleware/authorize");
const validate_1 = require("../../middleware/validate");
const permissions_1 = require("../../rbac/permissions");
const router = (0, express_1.Router)();
router.use(authenticate_1.authenticate);
router.get('/', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.OFFERS_READ), offer_controller_1.OfferController.list);
router.get('/:id', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.OFFERS_READ), offer_controller_1.OfferController.getById);
router.post('/', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.OFFERS_CREATE), (0, validate_1.validateBody)(offer_controller_1.createOfferSchema), offer_controller_1.OfferController.create);
router.put('/:id', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.OFFERS_UPDATE), (0, validate_1.validateBody)(offer_controller_1.updateOfferSchema), offer_controller_1.OfferController.update);
router.post('/:id/approve', (0, authorize_1.requirePermission)(permissions_1.PermissionCode.OFFERS_APPROVE), (0, validate_1.validateBody)(offer_controller_1.approveOfferSchema), offer_controller_1.OfferController.approve);
exports.default = router;
