import { RoleType } from './roles';
import { PermissionCode } from './permissions';

export const ROLE_PERMISSIONS: Record<RoleType, PermissionCode[]> = {
  [RoleType.CANDIDATE]: [
    PermissionCode.JOBS_READ,
    PermissionCode.CANDIDATES_READ,
    PermissionCode.CANDIDATES_CREATE,
    PermissionCode.CANDIDATES_UPDATE,
    PermissionCode.INTERVIEWS_READ,
    PermissionCode.OFFERS_READ,
    PermissionCode.NOTIFICATIONS_READ,
  ],

  [RoleType.INTERVIEWER]: [
    PermissionCode.ORGANIZATION_READ,
    PermissionCode.CANDIDATES_READ,
    PermissionCode.INTERVIEWS_READ,
    PermissionCode.EVALUATIONS_READ,
    PermissionCode.EVALUATIONS_CREATE,
    PermissionCode.EVALUATIONS_UPDATE,
    PermissionCode.NOTIFICATIONS_READ,
  ],

  [RoleType.HIRING_MANAGER]: [
    PermissionCode.ORGANIZATION_READ,
    PermissionCode.REQUISITIONS_READ,
    PermissionCode.REQUISITIONS_CREATE,
    PermissionCode.REQUISITIONS_UPDATE,
    PermissionCode.JOBS_READ,
    PermissionCode.CANDIDATES_READ,
    PermissionCode.INTERVIEWS_READ,
    PermissionCode.EVALUATIONS_READ,
    PermissionCode.OFFERS_READ,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.REPORTS_READ,
  ],

  [RoleType.RECRUITER]: [
    PermissionCode.ORGANIZATION_READ,
    PermissionCode.REQUISITIONS_READ,
    PermissionCode.REQUISITIONS_CREATE,
    PermissionCode.REQUISITIONS_UPDATE,
    PermissionCode.JOBS_READ,
    PermissionCode.JOBS_CREATE,
    PermissionCode.JOBS_UPDATE,
    PermissionCode.JOBS_PUBLISH,
    PermissionCode.CANDIDATES_READ,
    PermissionCode.CANDIDATES_CREATE,
    PermissionCode.CANDIDATES_UPDATE,
    PermissionCode.CANDIDATES_DELETE,
    PermissionCode.INTERVIEWS_READ,
    PermissionCode.INTERVIEWS_CREATE,
    PermissionCode.INTERVIEWS_UPDATE,
    PermissionCode.INTERVIEWS_DELETE,
    PermissionCode.EVALUATIONS_READ,
    PermissionCode.OFFERS_READ,
    PermissionCode.OFFERS_CREATE,
    PermissionCode.OFFERS_UPDATE,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.NOTIFICATIONS_MANAGE,
    PermissionCode.REPORTS_READ,
  ],

  [RoleType.APPROVER]: [
    PermissionCode.ORGANIZATION_READ,
    PermissionCode.REQUISITIONS_READ,
    PermissionCode.REQUISITIONS_APPROVE,
    PermissionCode.JOBS_READ,
    PermissionCode.CANDIDATES_READ,
    PermissionCode.EVALUATIONS_READ,
    PermissionCode.OFFERS_READ,
    PermissionCode.OFFERS_APPROVE,
    PermissionCode.REPORTS_READ,
  ],

  [RoleType.HR_MANAGER]: [
    PermissionCode.ORGANIZATION_READ,
    PermissionCode.ORGANIZATION_WRITE,
    PermissionCode.REQUISITIONS_READ,
    PermissionCode.REQUISITIONS_CREATE,
    PermissionCode.REQUISITIONS_UPDATE,
    PermissionCode.REQUISITIONS_APPROVE,
    PermissionCode.REQUISITIONS_DELETE,
    PermissionCode.JOBS_READ,
    PermissionCode.JOBS_CREATE,
    PermissionCode.JOBS_UPDATE,
    PermissionCode.JOBS_PUBLISH,
    PermissionCode.JOBS_DELETE,
    PermissionCode.CANDIDATES_READ,
    PermissionCode.CANDIDATES_CREATE,
    PermissionCode.CANDIDATES_UPDATE,
    PermissionCode.CANDIDATES_DELETE,
    PermissionCode.INTERVIEWS_READ,
    PermissionCode.INTERVIEWS_CREATE,
    PermissionCode.INTERVIEWS_UPDATE,
    PermissionCode.INTERVIEWS_DELETE,
    PermissionCode.EVALUATIONS_READ,
    PermissionCode.EVALUATIONS_CREATE,
    PermissionCode.EVALUATIONS_UPDATE,
    PermissionCode.OFFERS_READ,
    PermissionCode.OFFERS_CREATE,
    PermissionCode.OFFERS_UPDATE,
    PermissionCode.OFFERS_APPROVE,
    PermissionCode.OFFERS_DELETE,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.NOTIFICATIONS_MANAGE,
    PermissionCode.REPORTS_READ,
    PermissionCode.USERS_READ,
    PermissionCode.ROLES_READ,
    PermissionCode.AUDIT_LOGS_READ,
  ],

  [RoleType.ADMIN]: [
    PermissionCode.ORGANIZATION_READ,
    PermissionCode.ORGANIZATION_WRITE,
    PermissionCode.REQUISITIONS_READ,
    PermissionCode.REQUISITIONS_CREATE,
    PermissionCode.REQUISITIONS_UPDATE,
    PermissionCode.REQUISITIONS_APPROVE,
    PermissionCode.REQUISITIONS_DELETE,
    PermissionCode.JOBS_READ,
    PermissionCode.JOBS_CREATE,
    PermissionCode.JOBS_UPDATE,
    PermissionCode.JOBS_PUBLISH,
    PermissionCode.JOBS_DELETE,
    PermissionCode.CANDIDATES_READ,
    PermissionCode.CANDIDATES_CREATE,
    PermissionCode.CANDIDATES_UPDATE,
    PermissionCode.CANDIDATES_DELETE,
    PermissionCode.INTERVIEWS_READ,
    PermissionCode.INTERVIEWS_CREATE,
    PermissionCode.INTERVIEWS_UPDATE,
    PermissionCode.INTERVIEWS_DELETE,
    PermissionCode.EVALUATIONS_READ,
    PermissionCode.EVALUATIONS_CREATE,
    PermissionCode.EVALUATIONS_UPDATE,
    PermissionCode.OFFERS_READ,
    PermissionCode.OFFERS_CREATE,
    PermissionCode.OFFERS_UPDATE,
    PermissionCode.OFFERS_APPROVE,
    PermissionCode.OFFERS_DELETE,
    PermissionCode.NOTIFICATIONS_READ,
    PermissionCode.NOTIFICATIONS_MANAGE,
    PermissionCode.REPORTS_READ,
    PermissionCode.USERS_READ,
    PermissionCode.USERS_CREATE,
    PermissionCode.USERS_UPDATE,
    PermissionCode.USERS_DISABLE,
    PermissionCode.ROLES_READ,
    PermissionCode.ROLES_UPDATE,
    PermissionCode.AUDIT_LOGS_READ,
  ],
};
