ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "mustChangePassword" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "activationTokenHash" TEXT,
  ADD COLUMN IF NOT EXISTS "activationExpiresAt" TIMESTAMP(3);
